In [1]:
import numpy as np


In [3]:
np.array([2,5,7,9,])


array([2, 5, 7, 9])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
np.ones((10,3,3),dtype="int")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [12]:
np.full(8, 5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [14]:
np.full((2, 3),6, dtype ="float")

array([[6., 6., 6.],
       [6., 6., 6.]])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(start=3, stop=10, dtype="float")

array([3., 4., 5., 6., 7., 8., 9.])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.linspace(10,30,10)

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [25]:
np.random.rand(5, 3)

array([[0.85512494, 0.02581043, 0.60633462],
       [0.4072214 , 0.03845499, 0.64852675],
       [0.66563677, 0.0442369 , 0.02507505],
       [0.27245913, 0.59926219, 0.05036354],
       [0.63031931, 0.08122046, 0.1828132 ]])

In [26]:
np.random.randn(5)

array([ 0.49229708, -0.97569014, -0.91740713,  0.02186503,  0.49311291])

In [27]:
np.random.normal(20,5,(2,5))

array([[22.69043259, 19.93526682, 13.04074871, 24.27576984, 28.12133855],
       [18.84613574, 14.01525248, 19.19609393, 21.07704263, 21.28102057]])

In [33]:
ex = np.arange(2.5)
print(ex)

[0. 1. 2.]


In [48]:
import numpy as np

In [52]:
arrray = np.random.randint(5, 50, 20)

In [53]:
arrray

array([ 8, 37, 48, 32, 32, 32, 26, 29, 46, 41, 43, 36, 35, 21, 47, 33, 24,
       31, 27, 48])

In [56]:
arrray.min()

8

In [57]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])


In [58]:
np.concatenate([array1, array2])

array([1, 2, 3, 4, 5, 6, 7, 8])